server:
  port: 8080
  servlet:
    context-path: /jewelry/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jewelry"
    username : root
    password: password


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true