server:
  port: 8080
  servlet:
    context-path: /jewelry/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jewelry
    username: root
    password: 30122004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb_app;MODE=MYSQL
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true

jwt:
  signerKey: "csmtYZldbUGTyhzXVuNr4b3UM3JdbdGx3CRYju7Jr2IXJ52o7mmSA8ZWrYTXYWNM"
