server:
  port: 8080
  servlet:
    context-path: /jewelry/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jwe"
    username: root
    password: 30122004
    driverClassName: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "csmtYZldbUGTyhzXVuNr4b3UM3JdbdGx3CRYju7Jr2IXJ52o7mmSA8ZWrYTXYWNM"
