server:
  port: 8080
  servlet:
    context-path: /jewelry

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jewelry"
    username : root
    password: 30122004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true